name: thanxtory
description: Thanxtory is a third place of gratitude.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  like_button: ^2.0.4
  line_icons: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.2
  intl: ^0.17.0
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_analytics: ^9.1.0
  firebase_storage: ^10.2.7
  firebase_messaging: ^11.2.6
  path_provider: ^2.0.9
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.0.5
  material_floating_search_bar: ^0.3.7
  image_picker: ^0.8.4+10
  image_cropper: ^2.0.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png