name: thanxtory
description: Thanxtory is a third place of gratitude.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  bouncing_widget: ^2.0.0
  like_button: ^2.0.4
  line_icons: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.13
  anim_search_bar: ^2.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  cloud_firestore: ^3.1.8
  cloud_functions: ^3.2.7
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_analytics: ^9.1.0
  firebase_storage: ^10.2.7
  firebase_messaging: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf